### ISSUE TITLE
1.5.0 makes different layout behavior against 1.4.1

### ISSUE THREAD

**Issue by muukii** [sampettersson/Placement#10]
first of all, I appreciate your wondrous works.
I've made a small library that lays elements out in flow.

https://github.com/FluidGroup/swiftui-WrapLayout

Then I noticed the latest version 1.5.0 that runs something different against 1.4.1.
Actually, laying out does not work correctly.

For now, it's still just head up for you. I will investigate more about what's going on inside.

## iOS 15.x

1.4.1
<img width="439" alt="CleanShot 2023-06-12 at 14 18 30@2x" src="https://github.com/sampettersson/Placement/assets/1888355/358930ab-b1e8-4275-8039-fb3a66f2bf7a">

1.5.0 - all viewers are placed in same position.
<img width="439" alt="CleanShot 2023-06-12 at 14 17 57@2x" src="https://github.com/sampettersson/Placement/assets/1888355/55bb1235-69e1-4161-aafe-a7f1d09f21cc">

**Comment by sampettersson** [comment]
Oh, that's not great. I'll take a look when time permits to figure out why this is. Thanks for reporting!

**Comment by sampettersson** [comment]
Sorry for a very late investigation to this issue but I've found what seems to be causing this, and its due to the default implementation for `updateCache` that was changed in `1.5.0` to match how Apples Layout protocol does it where it recreates the cache each time its called. So in your case adding an `updateCache` method that is empty seems to solve the issue, like this:

`public func updateCache(_ cache: inout CacheStorage, subviews: Subviews) {}`

Closing this issue now, feel free to open again if the issue persists.
